// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPIMotos.Context;

namespace WebAPIMotos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPIMotos.Models.Adventure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Bateria")
                        .HasColumnType("float");

                    b.Property<int>("Cilindrada")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("Partida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<double>("PotênciaCV")
                        .HasColumnType("float");

                    b.Property<double>("Tanque")
                        .HasColumnType("float");

                    b.Property<int>("TorqueKfgm")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Adventures");
                });

            modelBuilder.Entity("WebAPIMotos.Models.OffRoad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Bateria")
                        .HasColumnType("float");

                    b.Property<int>("Cilindrada")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("Partida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<double>("PotênciaCV")
                        .HasColumnType("float");

                    b.Property<double>("Tanque")
                        .HasColumnType("float");

                    b.Property<int>("TorqueKfgm")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OffRoads");
                });

            modelBuilder.Entity("WebAPIMotos.Models.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Bateria")
                        .HasColumnType("float");

                    b.Property<int>("Cilindrada")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("Partida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<double>("PotênciaCV")
                        .HasColumnType("float");

                    b.Property<double>("Tanque")
                        .HasColumnType("float");

                    b.Property<int>("TorqueKfgm")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sports");
                });

            modelBuilder.Entity("WebAPIMotos.Models.Street", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Bateria")
                        .HasColumnType("float");

                    b.Property<int>("Cilindrada")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("Partida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<double>("PotênciaCV")
                        .HasColumnType("float");

                    b.Property<double>("Tanque")
                        .HasColumnType("float");

                    b.Property<int>("TorqueKfgm")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Streets");
                });

            modelBuilder.Entity("WebAPIMotos.Models.Touring", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Bateria")
                        .HasColumnType("float");

                    b.Property<int>("Cilindrada")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("Partida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<double>("PotênciaCV")
                        .HasColumnType("float");

                    b.Property<double>("Tanque")
                        .HasColumnType("float");

                    b.Property<int>("TorqueKfgm")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tourings");
                });
#pragma warning restore 612, 618
        }
    }
}
